### ISSUE TITLE
Create a Riot application request for the bot

### ISSUE THREAD

**Issue by ajoscram** [ajoscram/Jupi-Zordon-3400#18]
Currently, every request requires an API key which has to be refreshed every day. This is not sustainable. We can apply for a Riot token which doesn't expire here: https://developer.riotgames.com/docs/portal#product-registration_application-process

Apply the bot for a permanent API token on that link.
If it's not possible to do so, discuss it with the team.

**Comment by AivyMR** [comment]
![image](https://user-images.githubusercontent.com/37788748/131685089-9b3759d1-3809-40b7-8476-c7ec88fd6792.png)

Please notices that:
- We can't use this API for MMR or ELO calculation.
- This API its just for this project, if we want to make another project we must have another API.
- Publish a project that doesn't properly secure your API key.
- We can't use any of their official logos(Riot logos) but can use their art.

The complete "Terms of use" link for reference: https://developer.riotgames.com/terms
The complete "Legal Jibber Jabber" link for refence: https://www.riotgames.com/en/legal

**Comment by AivyMR** [comment]
![image](https://user-images.githubusercontent.com/37788748/131747185-d66fbd71-2c33-442d-9c9c-8902661d2da2.png)

**Comment by AivyMR** [comment]
![image](https://user-images.githubusercontent.com/37788748/132437877-89ae26e8-ea7d-4013-b7c3-4dcced14f838.png)

API key approved

**Comment by AivyMR** [comment]
API Key: RGAPI-b4f6c8e4-491b-4f4b-8fe6-62a7e2ad278f
